### ISSUE TITLE
插件无法使用，提示你的浏览器环境存在安全风险，隐私数据可能会被第三方获取。请卸载非官方插件后继续使用。

### ISSUE THREAD

**Issue by lovecn** [liuhao326/wereader#1]
直接在商店安装的 
https://chrome.google.com/webstore/detail/%E5%BE%AE%E4%BF%A1%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%E5%8A%A9%E6%89%8B/cmlenojlebcodibpdhmklglnbaghpdcg?hl=zh-CN

**Comment by liuhao326** [comment]
> 直接在商店安装的
> https://chrome.google.com/webstore/detail/%E5%BE%AE%E4%BF%A1%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%E5%8A%A9%E6%89%8B/cmlenojlebcodibpdhmklglnbaghpdcg?hl=zh-CN

请问这是什么时候的提醒？麻烦发一张图片。

**Comment by lovecn** [comment]
打开阅读页就提示这个 ，文字都出不来。

**Comment by liuhao326** [comment]
可能是浏览器的原因，可以卸载插件后重新下载试试
