### ISSUE TITLE
有计划支持Firefox吗？

### ISSUE THREAD

**Issue by YandLiu** [liuhao326/wereader#2]

**Comment by liuhao326** [comment]
嗯，计划会支持，我将会加快进度但可能不会很快。

**Comment by liuhao326** [comment]
已支持：[wereader](https://addons.mozilla.org/zh-CN/firefox/addon/%E5%BE%AE%E4%BF%A1%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%E5%8A%A9%E6%89%8B/)
