### ISSUE TITLE
希望可以合并导出标注和想法

### ISSUE THREAD

**Issue by ValenW** [liuhao326/wereader#5]
现在只能分开导出标注和想法, 但这样不方便整理, 希望可以一次性导出所有标注和想法, 就像App端一样

比如我自己就喜欢在App上边读边做标记和笔记, 然后一次性导出到OneNote上整理

但因为安卓剪贴板限制我不能保留格式地剪贴到安卓的OneNote上, 所以想到了网页端

**Comment by liuhao326** [comment]
感谢反馈~

v2.0.0 已在审核中。在新的版本中，可以通过在选项页中开启**导出标注包含想法**选项使得导出的标注中包含想法。
