### ISSUE TITLE
无法获取标注

### ISSUE THREAD

**Issue by Heinodaily** [liuhao326/wereader#6]
无法获取标注了，提示 该书无想法

**Comment by liuhao326** [comment]
之所以出现该情况是因为选项页中开启了“导出标注包含想法”选项，当书中没有想法而同时开启该选项时，将会出现你所遇到的标注无法导出的情况。临时的解决方案是关闭该选项再导出标注。

稍后我将会完善该问题。感谢反馈~ @Heinodaily

**Comment by liuhao326** [comment]
v2.2.1 已在审核中。新的版本能够在开启“导出标注包含想法”选项但没有想法的情况下正常导出标注。
