### ISSUE TITLE
一个请求

### ISSUE THREAD

**Issue by qiuqianyuanluo** [liuhao326/wereader#7]
非常感谢您开发这个小工具!!! 是目前为数不多的可以好好使用的微信阅读辅助。
想问下可不可以在导出高亮的时候提供纯文本的选项？就是不用 markdown 格式，或者只在标题的部分用 markdown。主要是目前的格式和我的编辑器总是不兼容，得一直修改替换，再就是它自动高亮的部分对我感觉不是很必要，本身就全部是高亮，不太需要再都突出显示啦。
非常感谢您的辛苦工作！

**Comment by liuhao326** [comment]
感谢反馈~

插件提供了设置选项可供您自定义导出效果。

比如，当希望所有标注都导出为纯文本时，只需要将`一级标注`、`二级标注`、`三级标注`的前后缀都设置为空。将各级标题的前缀设置为空则可以实现将标题导出为纯文本。

**Comment by qiuqianyuanluo** [comment]
找到设置的位置了，问题解决，感谢!!!
但是我有点没明白，微信读书的标注好像没有层级，为何会有一级二级三级三种呀？

再次感谢您~

发自我的iPhone

**Comment by liuhao326** [comment]
是的，在微信读书中，标注没有分层级，但是分三类：

![image](https://user-images.githubusercontent.com/51501079/97259292-73432880-1855-11eb-9579-73653d6cc44f.png)

分别是波浪线、马克笔和直线。

被直线标注的文本就是设置页面中所谓 `一级标注` ，被马克笔标注的文本是 `二级标注` ，被波浪线标注的文本是 `三级标注` 。

因为读者一般会在同一本书中使用不同的标注来分级别地标注不同内容，所以提供了这三个级别对应于三种标注，实现对不同类标注的设置。

**Comment by qiuqianyuanluo** [comment]
这个有点太厉害了吧，因为怀疑导出之后没差别，我一直只用的高亮。非常感谢您贴心的设计!!

让我来宣传下哈哈

发自我的iPhone

**Comment by liuhao326** [comment]
不用谢😀
